.gitignore
README.md
Vagrantfile
requirements.txt

Added vagrant file and readme to enable a dev environment to be created

Vagrant env setup

---

service/service.py
tests/test_service.py

1. Added location header to the response of create_products
2. Added corresponding tests to check location header.
Below are the nosetests results
```
404 Not Found: Product with id '2' was not found.
- Get a single product by its ID
404 Not Found: Product with id '0' was not found.
- Get a product that's not …
```

Issue19 add and check location header

---

service/service.py
tests/test_service.py

1. Updated service.py to support listing products #8.
2. Created some new tests in test_service.py for this function.
Below are the nosetests results:
```
404 Not Found: Product with id '1' was not found.
- Get a single product by its ID
- Get a list of Products
404 Not Found: Product with id '0' was not …
```

Issue8 Add Ability To List Products

---

service/models.py
service/service.py
tests/test_models.py
tests/test_service.py

1. Updated service.py and model.py to support querying products #9.
2. Created some new tests in test_models.py and test_service.py for this function.
Below are the nosetests results:
```
- Find Products by Category
- Find Products by Description
- Find Products by Name
- Find Products by Price
404 Not Found: Product with id '1' …
```

Issue9 Add Ability to Query Products

---

service/service.py
tests/test_service.py

I was able to write the skeleton of the api endpoint but we need to enhance it more when we get the details of the shopcart update endpoint. 
Below are the nosetests: 
```
- Find Products by Category
- Find Products by Description
- Find Products by Name
- Find Products by Price
404 Not Found: Product with id '1' was not found. …
```

Issue11 add ability to purchase products 

---

.pylintrc
requirements.txt

I set up pylint and found out that we have some improvements to be made on each .py file. I will paste them below. 
```
************* Module tests.test_service
tests/test_service.py:62:44: C0303: Trailing whitespace (trailing-whitespace)
tests/test_service.py:69:0: C0303: Trailing whitespace (trailing-whitespace)
tests/test_service.py:100:0: C0330: Wrong hanging indentation (add 3 spaces).
new_product["category"], test_product.category, "Categories do not match"
^  | (bad-continuation)
tests/test_service.py:103:0: C0330: Wrong hanging indentation (add 3 spaces).
new_product["description"], test_product.description, "Descriptions do not match"
^  | (bad-continuation)
tests/test_service.py:106:0: C0330: Wrong hanging indentation (add 3 spaces).
new_product["price"], test_product.price, …
```

issue27 Set Up Pylint

---

.pylintrc
service/__init__.py
service/models.py
service/service.py
tests/test_models.py
tests/test_service.py

Fixed all of the .py files to conform to PEP8 Style Guidelines. 
Below are the pylint test results:
```
************* Module service.models
service/models.py:41:0: C0303: Trailing whitespace (trailing-whitespace)
service/models.py:107:0: C0303: Trailing whitespace (trailing-whitespace)
service/models.py:157:0: C0303: Trailing whitespace (trailing-whitespace)
service/models.py:11:0: C0103: Constant name "db" doesn't conform to UPPER_CASE naming style (invalid-name)
service/models.py:15:4: W0107: Unnecessary pass statement (unnecessary-pass)
service/models.py:47:8: C0103: Attribute name "id" doesn't conform to snake_case naming style (invalid-name)
------------------------------------------------------------------
Your code has been rated at 9.10/10 (previous run: 9.10/10, +0.00) …
```

Issue29 fix code using pylint

---

README.md

Updated Readme to include the API Documentation and Database fields

issue31 updated README

---

README.md

Added the product_factory.py in README

Issue 32 added product_factory.py in README

---

.travis.yml
README.md

1. Added .travis.yml file for Travis CI configuration. 
I commented out the codecov part which should be uncommented in issue 36.
2. Added a badge for build status in the README file

Issue12 Set up a DevOps Pipeline for continuous integration

---

service/service.py
tests/test_service.py

Finished the implementation of the purchase endpoint and wrote test cases for it as well. 
Changed the implementation to just call two shopcart endpoints.
1. get shopcart to check if shopcart exists 
2. post in shopcart the shopcart item we want to add in the shopcart

Issue35 purchase product implementation

---

.travis.yml
README.md
requirements.txt

Added a Codcov badge to readme.md and update the .travis.yml file to run codecov

Issue36 set up code coverage

---

config.py
manifest.yml

Change config files for database connection

Changed config files for database connection

---

README.md
config.py
manifest.yml
service/models.py
service/service.py
tests/test_models.py
tests/test_service.py

Linked CD Pipeline with github and made the following changes to the code:
1. Fixed the pylint indention problem in the config.py 
2. Fixed the trailing white-spaces problem for pylint in both the tests and service folders 
3. Fixed README.md to add a new table for the urls (to make it more readable) 
4. linked cd pipeline with github

Issue 37 link CD pipeline with github 

---

tests/test_models.py
tests/test_service.py

added vcap_services to the test_models.py and test_service.py

Issue 42 set up build stage 

---

tests/test_service.py

I changed init_db in test_service from setUp to setUpClass 
```
def setUpClass(cls):
""" This runs once before the entire test suite """
init_db()
app.debug = False
app.testing = True
app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_URI

Issue 50 fix too many connections 

---

tests/test_models.py

added initdb to the setUpClass

issue 52 add initdb in the testmodels

---

Vagrantfile
features/environment.py
features/steps/product_steps.py
requirements.txt

1. Edited the Vagrantfile to add Chrome Headless and Selenium 
2. Edited the requirements.txt file to add the necessary libraries for BDD 
3. Added the features folder with the environment.py and products.feature file 
4. Added the steps folder with product_steps.py 
After running behave: 
```
(venv) vagrant@project:~$ cd /vagrant
(venv) vagrant@project:/vagrant$ behave
0 features passed, 0 failed, 0 skipped
0 scenarios passed, 0 failed, 0 skipped
0 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m0.000s
(venv) vagrant@project:/vagrant$

Issue 56 Create Features and steps 

---

tests/test_models.py
tests/test_service.py

I have added the db.session.close() in the test_model.py and test_service.py as suggested by the professor to see if this will solve the problem. If it doesn't solve the problem he also suggested that we could make a separate ElephantSQL instance just for testing

Issue 73 Fix Test Job Failure with CD Pipeline 

---

.travis.yml
config.py
manifest.yml
tests/test_models.py
tests/test_service.py

1. connected a new elephant sql database as user provided service in ibm cloud
2. changed the code and setting files for the test database
3. pasted the new vcap service environment variable in our pipeline

Issue77 Create an ElephantSQL test Database

---

requirements.txt

Added the urllib3 1.25.11 to fix the incompatibility with the requests library

Issue 79 add urllib3 to requirements file 

---

features/products.feature
features/steps/product_steps.py

Behave result:
```
Given the following products                             # features/steps/product_steps.py:21
03:04:58 web.1  | [2020-11-12 03:04:58 +0000] [INFO] [service] Request for product list
03:04:58 …
```

Issue62 add query in BDD feature file

---

service/service.py
tests/test_service.py

Fixed the statuscode checks in the code 
Fixed the url endpoints to match what we want to call from the shopcarts endpoints
Needs to be done: 
Find a way to test that our code will work on the shopcarts endpoints instead of mocks (will need consistent data)

Issue64 edit code forpurchase endpoint

---

features/products.feature
features/steps/product_steps.py

Behave Results: 
```
Given the following products                             # features/steps/product_steps.py:21 0.102s
When I visit the "Home Page"                             # …
```

Issue 59 Update BDD Feature

---

features/products.feature
service/service.py

Given the following products                             # features/steps/product_steps.py:21 0.033s
When I visit the "Home Page"                             # features/steps/product_steps.py:45 5.433s
Then I …

issue 61 add list in BDD feature file

---

features/products.feature
service/service.py
tests/test_service.py

- Create a product and raises an InvalidRequestError
- Find Products by Category
- Find Products by Description
- Find Products by Name
- Find Products by Price
- Update a product and raises an InvalidRequestError
Fields cannot be empty
- Create a new Product with bad request
404 Not Found: Product with id '1' …

Issue 92 fix bug to handle bad request

---

features/products.feature
features/steps/product_steps.py

Added simple delete test case to bdd

added delete bdd case

---

.codecov.yml
.pylintrc
service/models.py
service/service.py
tests/test_models.py
tests/test_service.py

Added some TDD tests for purchase endpoint but need some improvement such as a way to mock two different posts in a nested with clause. 
```
- Create a product and raises an InvalidRequestError
- Find Products by Category
- Find Products by Description
- Find Products by Name
- Find Products by Price
- Update a product and raises an InvalidRequestError
Fields cannot be empty
- Create a new Product with bad request
415 …
```

Issue90 edit purchase endpoint

---

features/products.feature
service/static/js/rest_api.js
service/templates/index.html

issue88 add amount field in UI

---

features/products.feature
features/steps/product_steps.py
service/static/js/rest_api.js

Given the following products                             # features/steps/product_steps.py:21 0.038s
When I visit the "Home Page"                             # features/steps/product_steps.py:45 0.213s
Then I …

Issue98 Fix Bug To Pass Integration Stage Update

---

.travis.yml
tests/test_models.py
tests/test_service.py

Added the db.drop_all back into the teardown functions and changed yaml to have a separate job for behave

Issue 103 Separate Jobs for Travis CI

---

features/products.feature
service/__init__.py
service/service.py

behave result:
```
(venv) vagrant@project:/vagrant$ behave
Given the following products                             # features/steps/product_steps.py:21 0.054s
When I visit the "Home Page" …
```

issue108 removed additional error message

---

service/service.py
service/static/js/rest_api.js

I was able to refactor the purchase endpoint to match all the api calls to the shopcart endpoint.

Issue 102 Refactor purchase endpoint

---

features/products.feature
features/steps/product_steps.py
service/service.py
service/static/js/rest_api.js
service/templates/index.html

Finalized the BDD Purchase endpoint and is working correctly now. I double checked the shopcart service to see if the amount was being updated in the shopcart for the userId.

Issue 63 finalized the bdd purchase

---

README.md
features/steps/product_steps.py
service/service.py
service/static/js/rest_api.js
tests/test_service.py

1. Refactored Products Collection using RestPlus
2. Removed "products/price" URL and changed front-end code accordingly
3. Removed content-type header in all the GET methods to avoid {"message": "The browser (or proxy) sent a request that this server could not understand."} error.

Issue105 Refactor Application using Flask-RestPlus ProductsCollection

---

README.md
service/service.py
service/static/js/rest_api.js
tests/test_service.py

Refactored purchase endpoint using restplus and changed frontend code and readme accordingly

Issue 106 Refactor Application using Flask-RestPlus PurchaseProduct

---

manifest.yml

Added a new Url for Dev and new prod App

Issue 76 Set up Deploy to Production Stage 

---

.pylintrc
features/products.feature
features/steps/product_steps.py
service/models.py
service/service.py
service/static/js/rest_api.js
tests/product_factory.py
tests/test_models.py
tests/test_service.py

Given the following products                             # features/steps/product_steps.py:21 0.030s
When I visit the "Home Page"                             # features/steps/product_steps.py:45 0.241s
Then I …

Issue113 Refactor Application Using Flask-Restplus Query

---

service/service.py
tests/test_service.py

fixed 500 internal error for purchase endpoint

issue 119 Bug Fix Purchase EndPoint

---

manifest.yml

Issue 121 Manifest.yml fix 

---

manifest.yml

Issue 123 Manfest YML bug 

---

manifest.yml

changed routes to be host and domain

Issue125 Manifest YML Change to Domain and Host 

---

manifest.yml

Issue127 Buildpack error 

---

service/service.py

I added the 400 response documentation for the purchase endpoint.

Issue 133 API Documentation 

---

service/models.py

I add added .contains in the find_name functions  so that we can show the results that have the words from the query but not necessarily have to be the exact same.

Issue 135 Change Query Name to Be Contains
